-- SQL Migration Script for Supabase
-- Reconstructed from api/index.js

-- 1. Tables: users & roles
CREATE TABLE IF NOT EXISTS roles (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    permissions TEXT[],
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    email VARCHAR(100) UNIQUE,
    role VARCHAR(50),
    status VARCHAR(20) DEFAULT 'Active',
    avatar TEXT,
    username VARCHAR(50) UNIQUE,
    password VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 2. Assets: Tanah, Bangunan, Kapling, Rumneg
CREATE TABLE IF NOT EXISTS assets_tanah (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(100) UNIQUE,
    category VARCHAR(100),
    luas NUMERIC,
    status VARCHAR(50),
    location TEXT,
    coordinates VARCHAR(100),
    map_boundary TEXT,
    area VARCHAR(100),
    folder_id INTEGER,
    source_file TEXT,
    jenis_bmn TEXT,
    kode_barang VARCHAR(50),
    nup VARCHAR(50),
    nama_barang TEXT,
    kondisi VARCHAR(50),
    luas_tanah_seluruhnya NUMERIC,
    nilai_perolehan NUMERIC,
    no_sertifikat VARCHAR(100),
    alamat_detail TEXT,
    kecamatan VARCHAR(100),
    kabupaten VARCHAR(100),
    provinsi VARCHAR(100),
    keterangan_bmn TEXT,
    kode_kota VARCHAR(50),
    no_psp VARCHAR(100),
    tgl_psp DATE,
    rt_rw VARCHAR(50),
    kelurahan_desa VARCHAR(100),
    tanggal_perolehan TEXT,
    tgl_sertifikat TEXT,
    occupant_name VARCHAR(100),
    occupant_rank VARCHAR(50),
    occupant_nrp VARCHAR(50),
    occupant_title VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assets_bangunan (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    code VARCHAR(100) UNIQUE,
    category VARCHAR(100),
    luas VARCHAR(50),
    status VARCHAR(50),
    location TEXT,
    coordinates VARCHAR(100),
    map_boundary TEXT,
    area VARCHAR(100),
    occupant_name TEXT,
    occupant_rank TEXT,
    occupant_nrp TEXT,
    occupant_title TEXT,
    status_penghuni TEXT,
    no_sip TEXT,
    tgl_sip TEXT,
    tipe_rumah TEXT,
    golongan TEXT,
    tahun_buat TEXT,
    asal_perolehan TEXT,
    mendapat_fasdin TEXT,
    kondisi TEXT,
    keterangan TEXT,
    alamat_detail TEXT,
    nup TEXT,
    kode_barang TEXT,
    nama_barang TEXT,
    luas_tanah VARCHAR(50),
    folder_id INTEGER,
    source_file TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assets_kapling (
    id SERIAL PRIMARY KEY, 
    name VARCHAR(255), 
    code VARCHAR(50), 
    category VARCHAR(100), 
    luas VARCHAR(50), 
    status VARCHAR(50), 
    location TEXT, 
    coordinates VARCHAR(100), 
    map_boundary TEXT, 
    area VARCHAR(100), 
    folder_id INTEGER,
    occupant_name VARCHAR(100), 
    occupant_rank VARCHAR(50), 
    occupant_nrp VARCHAR(50), 
    occupant_title VARCHAR(100),
    jenis_bmn VARCHAR(100), 
    kode_barang VARCHAR(50), 
    nup VARCHAR(50), 
    nama_barang VARCHAR(255), 
    kondisi VARCHAR(50),
    luas_tanah_seluruhnya VARCHAR(50), 
    tanah_yg_telah_bersertifikat VARCHAR(50), 
    tanah_yg_belum_bersertifikat VARCHAR(50),
    tanggal_perolehan VARCHAR(50), 
    nilai_perolehan NUMERIC, 
    no_sertifikat VARCHAR(100), 
    tgl_sertifikat VARCHAR(50),
    standar_satuan VARCHAR(50), 
    alamat_detail TEXT, 
    kecamatan VARCHAR(100), 
    kabupaten VARCHAR(100), 
    provinsi VARCHAR(100), 
    keterangan_bmn TEXT,
    kode_kota VARCHAR(50), 
    no_psp VARCHAR(100), 
    tgl_psp VARCHAR(50), 
    rt_rw VARCHAR(50), 
    kelurahan_desa VARCHAR(100),
    created_at TIMESTAMP DEFAULT NOW(), 
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assets_rumneg (
    id SERIAL PRIMARY KEY,
    occupant_name TEXT,
    occupant_rank TEXT,
    occupant_nrp TEXT,
    area TEXT,
    alamat_detail TEXT,
    longitude TEXT,
    latitude TEXT,
    status_penghuni TEXT,
    no_sip TEXT,
    tgl_sip TEXT,
    tipe_rumah TEXT,
    golongan TEXT,
    tahun_buat TEXT,
    asal_perolehan TEXT,
    mendapat_fasdin TEXT,
    kondisi TEXT,
    keterangan TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 3. Assets: Pemanfaatan & Diskes & Faslabuh
CREATE TABLE IF NOT EXISTS assets_pemanfaatan (
    id SERIAL PRIMARY KEY,
    objek TEXT,
    pemanfaatan TEXT,
    luas TEXT,
    bentuk_pemanfaatan TEXT,
    pihak_pks TEXT,
    no_pks TEXT,
    tgl_pks TEXT,
    nilai_kompensasi TEXT,
    jangka_waktu TEXT,
    no_persetujuan TEXT,
    tgl_persetujuan TEXT,
    no_ntpn TEXT,
    tgl_ntpn TEXT,
    longitude TEXT,
    latitude TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS assets_diskes (
    id SERIAL PRIMARY KEY,
    name TEXT,
    type TEXT,
    location TEXT,
    capacity TEXT,
    staff TEXT,
    status TEXT,
    description TEXT,
    longitude TEXT,
    latitude TEXT,
    tahun_beroperasi TEXT,
    sarana JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS faslabuh (
    id SERIAL PRIMARY KEY,
    lantamal TEXT,
    lanal_faslan TEXT,
    lokasi_dermaga TEXT,
    nama_dermaga TEXT,
    jenis_dermaga TEXT,
    panjang_m NUMERIC,
    lebar_m NUMERIC,
    kedalaman_m NUMERIC,
    luas_m2 NUMERIC,
    konstruksi TEXT,
    tahun_pembangunan TEXT,
    kapasitas_kapal TEXT,
    tonase_max NUMERIC,
    jumlah_tambat INTEGER,
    panjang_tambat_m NUMERIC,
    kondisi_dermaga TEXT,
    kondisi_lantai TEXT,
    kondisi_dinding TEXT,
    kondisi_fender TEXT,
    bollard TEXT,
    fender TEXT,
    tangga_kapal TEXT,
    lampu_dermaga TEXT,
    air_bersih TEXT,
    listrik TEXT,
    bbm TEXT,
    crane TEXT,
    elevasi_m NUMERIC,
    draft_m NUMERIC,
    lebar_apron_m NUMERIC,
    panjang_apron_m NUMERIC,
    fungsi_dermaga TEXT,
    keterangan TEXT,
    status_operasional TEXT,
    longitude TEXT,
    latitude TEXT,
    sandar_items JSONB,
    fotos JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- 4. Master Tables
CREATE TABLE IF NOT EXISTS master_asset_folders (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS master_asset_utama (
    id SERIAL PRIMARY KEY,
    unique_key VARCHAR(200) UNIQUE,
    jenis_bmn TEXT,
    kode_satker TEXT,
    nama_satker TEXT,
    kode_barang TEXT,
    nup TEXT,
    nama_barang TEXT,
    status_bmn TEXT,
    merk TEXT,
    tipe TEXT,
    kondisi TEXT,
    umur_aset NUMERIC,
    intra_extra TEXT,
    henti_guna TEXT,
    status_sbsn TEXT,
    status_bmn_idle TEXT,
    status_kemitraan TEXT,
    bpybds TEXT,
    usulan_barang_hilang TEXT,
    usulan_barang_rb TEXT,
    usul_hapus TEXT,
    hibah_dktp TEXT,
    konsesi_jasa TEXT,
    properti_investasi TEXT,
    jenis_dokumen TEXT,
    no_dokumen TEXT,
    no_bpkp TEXT,
    no_polisi TEXT,
    status_sertifikasi TEXT,
    jenis_sertifikat TEXT,
    no_sertifikat TEXT,
    nama_sertifikat TEXT,
    tanggal_buku_pertama TEXT,
    tanggal_perolehan TEXT,
    tanggal_penghapusan TEXT,
    nilai_perolehan_pertama NUMERIC,
    nilai_mutasi NUMERIC,
    nilai_perolehan NUMERIC,
    nilai_penyusutan NUMERIC,
    nilai_buku NUMERIC,
    luas_tanah_seluruhnya NUMERIC,
    luas_tanah_bangunan NUMERIC,
    luas_tanah_sarana NUMERIC,
    luas_tanah_kosong NUMERIC,
    luas_bangunan NUMERIC,
    luas_tapak_bangunan NUMERIC,
    luas_pemanfaatan NUMERIC,
    jumlah_lantai NUMERIC,
    jumlah_foto NUMERIC,
    status_bangunan TEXT,
    no_psp TEXT,
    tanggal_psp TEXT,
    alamat TEXT,
    rt_rw TEXT,
    kelurahan_desa TEXT,
    kecamatan TEXT,
    kab_kota TEXT,
    kode_kab_kota TEXT,
    provinsi TEXT,
    kode_provinsi TEXT,
    kode_pos TEXT,
    sbsk TEXT,
    optimalisasi TEXT,
    penghuni TEXT,
    pengguna TEXT,
    kode_kpknl TEXT,
    uraian_kpknl TEXT,
    uraian_kanwil_djkn TEXT,
    nama_kl TEXT,
    nama_e1 TEXT,
    nama_korwil TEXT,
    kode_register TEXT,
    lokasi_ruang TEXT,
    jenis_identitas TEXT,
    no_identitas TEXT,
    no_stnk TEXT,
    nama_pengguna TEXT,
    status_pmk TEXT,
    longitude TEXT,
    latitude TEXT,
    lanal TEXT,
    photos TEXT,
    identifikasi_aset TEXT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Seed Initial Data
INSERT INTO roles (name, description, permissions) VALUES 
('Super Admin', 'Full access to all system features', ARRAY['all']),
('Admin', 'Administrative access', ARRAY['manage_users', 'manage_content']),
('User', 'Standard user access', ARRAY['read_content'])
ON CONFLICT (name) DO NOTHING;

INSERT INTO users (name, email, role, status, username, password) 
VALUES ('Administrator', 'admin@kodaeral.com', 'Super Admin', 'Active', 'kodaeral', 'kodaeral')
ON CONFLICT (username) DO NOTHING;
